# costmap params
robot_radius: 0.6

geometric_dilation_alpha: 1.5
geometric_gaussian_sigma: 2.5
geometric_cost_threshold: 0.8
geometric_cost_amplification: 1.3

semantic_dilation_alpha: 1.0
semantic_gaussian_sigma: 1.5
semantic_cost_threshold: 0.75
semantic_cost_amplification: 1.0

is_fusion_using_max: true

aggressive_level: 1

is_geo_treat_unknown_as_obstacle: true
is_sem_treat_unknown_as_obstacle: true

# planner params
planning_time_s: 0.1
is_planning_debug: false